export const ACCOUNT_DELETION_WAIT_HOURS = 24;

export const ACCOUNT_DELETION_WAIT_MS =
  ACCOUNT_DELETION_WAIT_HOURS * 60 * 60 * 1000;

export const ACCOUNT_DELETION_VERIFICATION_TTL_MS = 30 * 60 * 1000; // 30 minutes
